Repository opendatahub-io/lm-evaluation-harness, pull requests merged in 2024-11, with the labels that each got.

#6 feat(tests): add GHA checks to PRs into release branches
  .github/workflows/new_tasks.yml
Labels: kind/enhancement

#5 fix: cherry-pick TLS validation skip and Watsonx support from main into release-0.4.5
  docs/API_guide.md
  lm_eval/models/__init__.py
  lm_eval/models/api_models.py
  lm_eval/models/ibm_watsonx_ai.py
  pyproject.toml
Labels: cherry-pick

#7 fix(dependencies): Pin dependencies
  pyproject.toml
Labels: dependencies

#8 fix(test): Add GH unit test runs to release branches
  .github/workflows/unit_tests.yml
Labels: kind/enhancement

#9 fix(test): Keep only Python 3.11 in GHAs
  .github/workflows/unit_tests.yml
Labels: kind/enhancement

#10 chore(dependencies): Add Watsonx LLM support to LMEval Job image
  Dockerfile.lmes-job
  pyproject.toml
Labels: dependencies

#12 feat(dependencies): Add unitxt as an explicit dependency
  pyproject.toml
Labels: kind/enhancement, dependencies

#11 use local unitxt if it exits for evaluation
  lm_eval/tasks/unitxt/task.py
Labels: kind/enhancement
