Repository opendatahub-io/lm-evaluation-harness, pull requests merged in 2025-02, with the labels that each got.

#17 fix: Replace UNITXT_ARTIFACTORIES with UNITXT_CATALOGS
  Dockerfile.lmes-job
Labels: kind/bug, kind/enhancement

#18 feat: Add S3 asset downloader script
  pyproject.toml
  scripts/s3_downloader.py
Labels: kind/enhancement

#22 Changing base image to python-311:latest
  Dockerfile.lmes-job
Labels: dependencies

#20 fix: switch to numeric user instead of default
  Dockerfile.lmes-job
Labels: kind/bug
